### ISSUE TITLE
Contact abilities

### ISSUE THREAD

**Issue by SiddhantGreen** [EternalCode/battle_engine#116]
## If-contact
- [x] Effect Spore
- [x] Static
- [x] Rough Skin
- [x] Poison Point
- [x] Flame Body
- [x] Cute Charm
- [x] Aftermath
- [x] Poison Touch
- [x] Mummy
- [x] Iron Barbs
- [x] Gooey
- [x] Tangling Hair
- [x] Pickpocket

**Comment by EternalCode** [comment]
Done. Pickpocket may need extra testing when items are added.
