### ISSUE TITLE
Damage Mitigation abilities

### ISSUE THREAD

**Issue by EternalCode** [EternalCode/battle_engine#129]
## Damage block
- [x] Battle Armor
- [x] Sturdy
- [x] Thick Fat
- [x] Shell Armor(*critical)
- [x] Heatproof
- [x] Filter
- [x] Solid Rock(*same as filter)
- [x] Friend Guard
- [x] Multiscale
- [x] Fur Coat
- [x] Water Bubble
- [x] Fluffy(*boosted when hit by fire-type)
- [x] Shadow Shield
- [x] Prism Armor

**Comment by KDSKardabox** [comment]
Solid Rock, Filter, Prism Armor are done.

**Comment by EternalCode** [comment]
Done.
