### ISSUE TITLE
Damage amplify abilities

### ISSUE THREAD

**Issue by EternalCode** [EternalCode/battle_engine#131]
### damage
- [x] Hustle(*only boost physical move)
- [x] Rivalry
- [x] Iron Fist
- [x] Adaptability
- [x] Sniper(boost critical damage)
- [x] Technician
- [x] Tinted Lens
- [x] Reckless
- [x] Sheer Force
- [x] Analytic
- [x] Strong Jaw
- [x] Mega Launcher
- [x] Tough Claws
- [x] Dark Aura
- [x] Fairy Aura
- [x] Aura Break(reverse aura ability effect )
- [x] Steelworker
- [x] Battery(ally move)

**Comment by SiddhantGreen** [comment]
Adaptability, Tinted Lens, Mega Launcher are done

**Comment by EternalCode** [comment]
Complete
