### ISSUE TITLE
Easy Moves

### ISSUE THREAD

**Issue by EternalCode** [EternalCode/battle_engine#47]
## Easy difficulty

Moves in this category will generally only require an assignment or addition of a move_procs structure to get working. They're very simple! Note that it's possible some of the moves in this list are done simply by virtue of the engine. For example, Strength has no additional effect, just a power. This move would be done by the engine at no labor cost for the creator. I have listed such moves because the moves table is currently computer generated and it would be nice if someone can double check if everything about that specific move was generated correctly!

- [x] Flamethrower
- [x] Water Gun
- [x] Hydro Pump
- [x] Ice Beam
- [x] Bubble Beam
- [x] Aurora Beam
- [x] Peck
- [x] Drill Peck
- [x] Submission
- [x] Strength
- [x] Mega Drain
- [x] Razor Leaf
- [x] Poison Powder
- [x] Stun Spore
- [x] Sleep Powder
- [x] String Shot
- [x] Thunder Shock
- [x] Thunderbolt
- [x] Rock Throw
- [x] Toxic
- [x] Confusion
- [x] Psychic
- [x] Hypnosis
- [x] Meditate
- [x] Agility
- [x] Quick Attack
- [x] Screech
- [x] Double Team
- [x] Recover
- [x] Harden
- [x] Smokescreen
- [x] Confuse Ray
- [x] Withdraw
- [x] Defense Curl
- [x] Egg Bomb
- [x] Lick
- [x] Smog
- [x] Sludge
- [x] Bone Club
- [x] Fire Blast
- [x] Hyper Beam
- [x] Frenzy Plant
- [x] Blast Burn
- [x] Hydro Cannon
- [x] Giga Impact
- [x] Rock Wrecker
- [x] Roar of Time
- [x] Prismatic Laster
- [x] Waterfall
- [x] Swift
- [x] Spike Cannon
- [x] Amnesia
- [x] Kinesis
- [x] Soft-Boiled
- [x] Glare
- [x] Poison Gas
- [x] Barrage
- [x] Leech life
- [x] Lovely Kiss
- [x] Bubble
- [x] Dizzy Punch
- [x] Spore
- [x] Flash
- [x] Splash
- [x] Acid Armor
- [x] Crabhammer
- [x] Fury Swipes
- [x] Bonemerang
- [x] Rock Slide
- [x] Hyper Fang
- [x] Sharpen
- [x] Slash
- [x] Flame Wheel
- [x] Aeroblast
- [x] Cotton Spore
- [x] Powder Snow
- [x] Mach Punch
- [x] Scary Face
- [x] Feint Attack
- [x] Sweet Kiss
- [x] Sludge Bomb
- [x] Mud-slap
- [x] Octazooka
- [x] Zap Cannon
- [x] Icy Wind
- [x] Bone Rush
- [x] Giga Drain
- [x] Charm
- [x] Swagger
- [x] Milk Drink
- [x] Spark
- [x] Steel Wing
- [x] Sacred Fire
- [x] Dynamic Punch
- [x] Mega Horn
- [x] Dragon Breath
- [x] Sweet Scent
- [x] Iron Tail
- [x] Metal Claw
- [x] Vital Throw
- [x] Cross Chop
- [x] Crunch
- [x] Extreme Speed
- [x] Shadow Ball
- [x] Rock Smash
- [x] Heat Wave
- [x] Flatter
- [x] Will-O-Wisp
- [x] Superpower
- [x] Tail Glow
- [x] Luster Purge
- [x] Mist Ball
- [x] Feather Dance
- [x] Teeter Dance
- [x] Blaze Kick
- [x] Needle Arm
- [x] Slack Off
- [x] Hyper Voice
- [x] Poison Fang
- [x] Crush Claw
- [x] Meteor Mash
- [x] Astonish
- [x] Fake Tears
- [x] Air Cutter
- [x] Overheat
- [x] Rock Tomb
- [x] Silver Wind
- [x] Metal Sound
- [x] Grass Whistle
- [x] Tickle
- [x] Cosmic Power
- [x] Signal Beam
- [x] Shadow Punch
- [x] Extrasensory
- [x] Muddy Water
- [x] Bullet Seed
- [x] Aerial Ace
- [x] Icicle Spear
- [x] Iron Defense
- [x] Howl
- [x] Dragon Claw
- [x] Bulk Up
- [x] Mud Shot
- [x] Poison Tail
- [x] Volt Tackle
- [x] Magical Leaf
- [x] Calm Mind
- [x] Leaf Blade
- [x] Dragon Dance
- [x] Rock Blast
- [x] Shock Wave
- [x] Water Pulse
- [x] Psycho Boost
- [x] Hammer Arm
- [x] Close Combat
- [x] Sucker Punch
- [x] Flare Blitz
- [x] Force Palm
- [x] Aura Sphere
- [x] Rock Polish
- [x] Dark Pulse
- [x] Night Slash
- [x] Aqua Tail
- [x] Seed Bomb
- [x] Air Slash
- [x] X-Scissor
- [x] Dragon Pulse
- [x] Power Gem
- [x] Drain Punch
- [x] Vacuum Wave
- [x] Focus Blast
- [x] Energy Ball
- [x] Brave Bird
- [x] Earth Power
- [x] Nasty Plot
- [x] Bullet Punch
- [x] Ice Shard
- [x] Shadow Claw
- [x] Thunder Fang
- [x] Ice Fang
- [x] Fire Fang
- [x] Shadow Sneak
- [x] Mud Bomb
- [x] Psycho Cut
- [x] Zen Headbutt
- [x] Flash Cannon
- [x] Rock Climb
- [x] Draco Meteor
- [x] Discharge
- [x] Lava Plume
- [x] Leaf Storm
- [x] Power Whip
- [x] Cross Poison
- [x] Gunk Shot
- [x] Iron Head
- [x] Magnet Bomb
- [x] Stone Edge
- [x] Chatter
- [x] Chargebeam
- [x] Wood Hammer
- [x] Aqua Jet
- [x] Attack Order
- [x] Defend Order
- [x] Heal Order
- [x] Head Smash
- [x] Double Hit
- [x] Spacial Rend
- [x] Dark Void
- [x] Seed Flare
- [x] Ominous Wind
- [x] Hone Claws
- [x] Psyshock
- [x] Flame Burst
- [x] Sludge Wave
- [x] Quiver Dance
- [x] Flame Charge
- [x] Coil
- [x] Low Sweep
- [x] Acid Spray
- [x] Scald
- [x] Inferno
- [x] Struggle Bug
- [x] Bulldoze
- [x] Frost Breath
- [x] Work Up
- [x] Electro Web
- [x] Wild Charge
- [x] Drill Run
- [x] Dual Chop
- [x] Heart Stamp
- [x] Horn Leech
- [x] Razor Shell
- [x] Leaf Tornado
- [x] Cotton Guard
- [x] Nightdaze
- [x] Psystrike
- [x] Tail Slap
- [x] Head Charge
- [x] Gear Grind
- [x] Searing Shot
- [x] Secret Sword
- [x] Glaciate
- [x] Bolt Strike
- [x] Blue Flare
- [x] Fiery Dance
- [x] Snarl
- [x] Icicle Crash
- [x] V-create
- [x] Noble Roar
- [x] Parabolic Charge
- [x] Disarming Voice
- [x] Draining Kiss
- [x] Play Rough
- [x] Fairy Wind
- [x] Moonblast
- [x] Boomburst
- [x] Play Nice
- [x] Confide
- [x] Mystical Fire
- [x] Eerie Impulse
- [x] Happy Hour
- [x] Dazzling Gleam
- [x] Celebrate
- [x] Hold Hands
- [x] Baby-Doll-Eyes
- [x] Power-up Punch
- [x] Oblivion Wing
- [x] Land's Wrath
- [x] Light of Ruin
- [x] Origin Pulse
- [x] Precipice Blades
- [x] Hyperspace Fury
- [x] Mirror Shot
- [x] Ice Hammer
- [x] High Horsepower
- [x] Leafage
- [x] Toxic Thread
- [x] Lunge
- [x] Fire Lash
- [x] Smart Strike
- [x] Trop Kick
- [x] Clanging Scales
- [x] Psychic Fangs
- [x] Dragon Hammer
- [x] Brutal Swing
- [x] Fleur Cannon
- [x] Shadow Bone
- [x] Accelerock
- [x] Liquidation
- [x] Tearful Look
- [x] Mind Blown
- [x] Plasma Fists
- [x] Zing Zap
- [x] Bug Buzz
- [x] Barrier

**Comment by Delta456** [comment]
Cross Chop need to be moved to Medium Difficulty.

**Comment by EternalCode** [comment]
@Delta456 For moves that have increased crit ratio, add the `.crit ratio` flag. See Karate Chop:
```c
    {
    /*Karate Chop*/
    .name = _("Karate Chop"),
    .accuracy = 100,
    .base_power = 50,
    .description = (pchar*)Karate_Chop_desc,
    .pp = 25,
    .crit_ratio = 1,
    .category = MOVE_PHYSICAL,
    .type = MTYPE_FIGHTING,
    .m_flags = FLAG_CONTACT | FLAG_MIRROR | FLAG_PROTECT | FLAG_TARGET,
    .procs = &basic_proc,
    }
```

**Comment by Delta456** [comment]
Ok, I got it.

**Comment by EternalCode** [comment]
@Delta456 What do you mean? It's not a medium difficulty move as it only requires an additional field for the increased crit ratio. There is no added code, as the effect is only `Cross Chop deals damage and has an increased critical hit ratio.`.

**Comment by Delta456** [comment]
Ok, Sorry man. 

I apologize for not noticing that. 😅

**Comment by Delta456** [comment]
Heart Swap should be moved to Medium Difficulty.

**Comment by Delta456** [comment]
Autotomize
Circle Throw
Psyshock
are not easy moves.

**Comment by Delta456** [comment]
Autotomize, Circle Throw and Psychshock should be moved to Medium.

**Comment by Delta456** [comment]
Incinerate and Heal Pulse are Medium too. 😅

**Comment by EternalCode** [comment]
The medium moves please don't mark as finished in your PR :+1:

**Comment by EternalCode** [comment]
@Delta456 Psyshock is doable. It requires just the `FLAG_CATEGORY_OVERRIDE` flag to be appended to it.

**Comment by Delta456** [comment]
I am sorry for my mistakes.

**Comment by Delta456** [comment]
_Night Daze_ is done my me in the previous commit.

**Comment by EternalCode** [comment]
Night Daze?

**Comment by EternalCode** [comment]
Completed
