### ISSUE TITLE
Abilities todo list

### ISSUE THREAD

**Issue by EternalCode** [EternalCode/battle_engine#99]
- [ ] Stench
- [ ] Drizzle
- [ ] Speed Boost
- [ ] Battle Armor
- [ ] Sturdy
- [ ] Damp
- [x] Limber
- [ ] Sand Veil
- [ ] Static
- [ ] Volt Absorb
- [ ] Water Absorb
- [ ] Oblivious
- [ ] Cloud Nine
- [ ] Compoundeyes
- [x] Insomnia
- [ ] Color Change
- [x] Immunity
- [ ] Flash Fire
- [ ] Shield Dust
- [ ] Own Tempo
- [ ] Suction Cups
- [ ] Intimidate
- [ ] Shadow Tag
- [ ] Rough Skin
- [ ] Wonder Guard
- [ ] Levitate
- [ ] Effect Spore
- [ ] Synchronize
- [ ] Clear Body
- [ ] Natural Cure
- [ ] Lightningrod
- [ ] Serene Grace
- [ ] Swift Swim
- [ ] Chlorophyll
- [ ] Illuminate
- [ ] Trace
- [ ] Huge Power
- [ ] Poison Point
- [ ] Inner Focus
- [ ] Magma Armor
- [ ] Water Veil
- [ ] Magnet Pull
- [ ] Soundproof
- [ ] Rain Dish
- [ ] Sand Stream
- [ ] Pressure
- [ ] Thick Fat
- [ ] Early Bird
- [ ] Flame Body
- [ ] Run Away
- [ ] Keen Eye
- [ ] Hyper Cutter
- [ ] Pickup
- [ ] Truant
- [ ] Hustle
- [ ] Cute Charm
- [ ] Plus
- [ ] Minus
- [ ] Forecast
- [ ] Sticky Hold
- [ ] Shed Skin
- [ ] Guts
- [ ] Marvel Scale
- [ ] Liquid Ooze
- [ ] Overgrow
- [ ] Blaze
- [ ] Torrent
- [ ] Swarm
- [ ] Rock Head
- [ ] Drought
- [ ] Arena Trap
- [ ] Vital Spirit
- [ ] White Smoke
- [ ] Pure Power
- [ ] Shell Armor
- [ ] Air Lock
- [ ] Tangled Feet
- [ ] Motor Drive
- [ ] Rivalry
- [ ] Steadfast
- [ ] Snow Cloak
- [ ] Gluttony
- [ ] Anger Point
- [ ] Unburden
- [ ] Heatproof
- [x] Simple
- [ ] Dry Skin
- [ ] Download
- [ ] Iron Fist
- [ ] Poison Heal
- [ ] Adaptability
- [ ] Skill Link
- [ ] Hydration
- [ ] Solar Power
- [ ] Quick Feet
- [ ] Normalize
- [ ] Sniper
- [ ] Magic Guard
- [ ] No Guard
- [ ] Stall
- [ ] Technician
- [ ] Leaf Guard
- [ ] Klutz
- [ ] Mold Breaker
- [ ] Super Luck
- [ ] Aftermath
- [ ] Anticipation
- [ ] Forewarn
- [ ] Unaware
- [ ] Tinted Lens
- [ ] Filter
- [ ] Slow Start
- [ ] Scrappy
- [ ] Storm Drain
- [ ] Ice Body
- [ ] Solid Rock
- [ ] Snow Warning
- [ ] Honey Gather
- [ ] Frisk
- [ ] Reckless
- [ ] Multitype
- [ ] Flower Gift
- [ ] Bad Dreams
- [ ] Pickpocket
- [ ] Sheer Force
- [x] Contrary
- [ ] Unnerve
- [ ] Defiant
- [ ] Defeatist
- [ ] Cursed Body
- [ ] Healer
- [ ] Friend Guard
- [ ] Weak Armor
- [ ] Heavy Metal
- [ ] Light Metal
- [ ] Multiscale
- [ ] Toxic Boost
- [ ] Flare Boost
- [ ] Harvest
- [ ] Telepathy
- [ ] Moody
- [ ] Overcoat
- [ ] Poison Touch
- [ ] Regenerator
- [ ] Big Pecks
- [ ] Sand Rush
- [ ] Wonder Skin
- [ ] Analytic
- [ ] Illusion
- [ ] Imposter
- [ ] Infiltrator
- [ ] Mummy
- [ ] Moxie
- [ ] Justified
- [ ] Rattled
- [ ] Magic Bounce
- [ ] Sap Sipper
- [ ] Prankster
- [ ] Sand Force
- [ ] Iron Barbs
- [ ] Zen Mode
- [ ] Victory Star
- [ ] Turboblaze
- [ ] Teravolt
- [ ] Aroma Veil
- [ ] Flower Veil
- [ ] Cheek Pouch
- [ ] Protean
- [ ] Fur Coat
- [ ] Magician
- [ ] Bulletproof
- [ ] Competitive
- [ ] Strong Jaw
- [ ] Refrigerate
- [ ] Sweet Veil
- [ ] Stance Chang
- [ ] Gale Wings
- [ ] MegaLauncher
- [ ] Grass Pelt
- [ ] Symbiosis
- [ ] Tough Claws
- [ ] Pixilate
- [ ] Gooey
- [ ] Aerilate
- [ ] Parentl Bond
- [ ] Dark Aura
- [ ] Fairy Aura
- [ ] Aura Break
- [ ] PrimordalSea
- [ ] Desolat Land
- [ ] Delta Stream
- [ ] Stamina
- [ ] Wimp Out
- [ ] Emergncy Ext
- [ ] WtrCompacton
- [ ] Merciless
- [ ] Shields Down
- [ ] Stakeout
- [ ] Water Bubble
- [ ] Steelworker
- [ ] Berserk
- [ ] Slush Rush
- [ ] Long Reach
- [ ] Liquid Voice
- [ ] Triage
- [ ] Galvanize
- [ ] Surge Surfer
- [ ] Schooling
- [ ] Disguise
- [ ] Battle Bond
- [ ] PwrConstrct
- [ ] Corrosion
- [ ] Comatose
- [ ] QunlyMajesty
- [ ] Innards Out
- [ ] Dancer
- [ ] Battery
- [ ] Fluffy
- [ ] Dazzling
- [ ] Soul-Heart
- [ ] Tanglng Hair
- [ ] Receiver
- [ ] PwrofAlchemy
- [ ] Beast Boost
- [ ] RKS System
- [ ] ElectrcSurge
- [ ] PsychicSurge
- [ ] Misty Surge
- [ ] Grassy Surge
- [ ] FulMetalBody
- [ ] ShadowShield
- [ ] Prism Armor
- [ ] Neuroforce

**Comment by Delta456** [comment]
Can you explain me how to do this?

**Comment by SiddhantGreen** [comment]
@EternalCode  please close this issue

**Comment by EternalCode** [comment]
Closed due to new issues opening with more detail and categorization.
